# -*- coding: utf-8 -*-
"""Movie recommendation system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mb7XOjoIYZDWzMLqW5lwgoHN_X0xtk1C
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ── Dataset ────────────────────────────────────────────────────────────────────
data = {
    "title": [
        "Avatar", "Titanic", "Avengers", "Iron Man", "The Notebook",
        "Inception", "Interstellar", "The Dark Knight", "Joker", "Frozen",
        "Gladiator", "Black Panther", "Thor", "Doctor Strange", "Captain America",
        "Hulk", "Spider-Man", "Deadpool", "Logan", "X-Men",
        "Harry Potter", "Fantastic Beasts", "Lord of the Rings", "Hobbit", "Star Wars",
        "Rogue One", "The Matrix", "John Wick", "Mission Impossible", "Top Gun",
        "Jurassic Park", "Jurassic World", "Transformers", "Pacific Rim", "Godzilla",
        "King Kong", "The Lion King", "Aladdin", "Beauty and the Beast", "Cinderella",
        "Moana", "Coco", "Up", "Toy Story", "Finding Nemo",
        "Shrek", "Kung Fu Panda", "How to Train Your Dragon", "Madagascar", "Ice Age",
        "Despicable Me", "Minions", "Zootopia", "Encanto", "Inside Out",
        "The Conjuring", "Annabelle", "Insidious", "It", "The Nun",
        "A Quiet Place", "Bird Box", "Get Out", "Us", "Smile",
        "The Shawshank Redemption", "Forrest Gump", "The Green Mile", "Fight Club", "Se7en",
        "The Social Network", "The Wolf of Wall Street", "Moneyball", "The Big Short", "Steve Jobs",
        "3 Idiots", "Dangal", "PK", "Lagaan", "Bahubali",
        "RRR", "KGF", "Pushpa", "Drishyam", "Andhadhun",
        "Kabir Singh", "Chhichhore", "Zindagi Na Milegi Dobara", "Dil Chahta Hai", "Rockstar",
        "Raees", "Sultan", "War", "Pathaan", "Tiger Zinda Hai",
        "Housefull", "Golmaal", "Hera Pheri", "Welcome", "Bhool Bhulaiyaa"
    ],
    "genres": [
        "Action SciFi", "Romance Drama", "Action Superhero", "Action Superhero", "Romance Drama",
        "SciFi Thriller", "SciFi Drama", "Action Crime", "Crime Drama", "Animation Family",
        "Action Drama", "Action Superhero", "Action Fantasy", "Action Fantasy", "Action Superhero",
        "Action Superhero", "Action Superhero", "Action Comedy", "Action Drama", "Action Superhero",
        "Fantasy Adventure", "Fantasy Adventure", "Fantasy Adventure", "Fantasy Adventure", "SciFi Adventure",
        "SciFi Action", "SciFi Action", "Action Thriller", "Action Thriller", "Action Drama",
        "SciFi Adventure", "SciFi Adventure", "Action SciFi", "Action SciFi", "Action SciFi",
        "Adventure Fantasy", "Animation Family", "Animation Fantasy", "Animation Romance", "Animation Fantasy",
        "Animation Adventure", "Animation Drama", "Animation Adventure", "Animation Family", "Animation Adventure",
        "Animation Comedy", "Animation Action", "Animation Fantasy", "Animation Comedy", "Animation Adventure",
        "Animation Comedy", "Animation Comedy", "Animation Crime", "Animation Musical", "Animation Drama",
        "Horror Thriller", "Horror Thriller", "Horror Thriller", "Horror Thriller", "Horror Thriller",
        "Horror Thriller", "Horror Thriller", "Horror Thriller", "Horror Thriller", "Horror Thriller",
        "Drama", "Drama", "Drama", "Drama Thriller", "Crime Thriller",
        "Biography Drama", "Biography Drama", "Sports Drama", "Finance Drama", "Biography Drama",
        "Comedy Drama", "Sports Drama", "Comedy Drama", "Sports Drama", "Action Drama",
        "Action Drama", "Action Drama", "Action Drama", "Thriller Drama", "Thriller Crime",
        "Romance Drama", "Comedy Drama", "Comedy Drama", "Drama", "Romance Drama",
        "Action Drama", "Sports Drama", "Action Thriller", "Action Thriller", "Action Thriller",
        "Comedy", "Comedy", "Comedy", "Comedy", "Comedy Horror"
    ]
}

df = pd.DataFrame(data)
df.to_csv("movies.csv", index=False)
print("✅ CSV saved — {} movies".format(len(df)))


# ── Model ──────────────────────────────────────────────────────────────────────
def train_model(csv_path="movies.csv"):
    """Load data and compute TF-IDF cosine similarity matrix."""
    df = pd.read_csv(csv_path).dropna(subset=["title", "genres"])
    df["title"] = df["title"].str.strip()
    df["genres"] = df["genres"].str.strip()
    df = df.drop_duplicates(subset="title").reset_index(drop=True)

    # TF-IDF weighs rarer genre tokens higher → better discrimination than raw counts
    tfidf = TfidfVectorizer()
    vectors = tfidf.fit_transform(df["genres"])
    similarity = cosine_similarity(vectors)

    return df, similarity


# ── Fuzzy title lookup ─────────────────────────────────────────────────────────
def find_closest_title(query, titles):
    """
    Case-insensitive substring match first; falls back to
    character-overlap scoring so typos still find results.
    """
    query_lower = query.lower().strip()
    title_lower = [t.lower() for t in titles]

    # 1. Exact match
    if query_lower in title_lower:
        return titles[title_lower.index(query_lower)]

    # 2. Substring match
    matches = [t for t, tl in zip(titles, title_lower) if query_lower in tl]
    if matches:
        return matches[0]

    # 3. Character-overlap fallback (handles minor typos)
    def overlap(a, b):
        return len(set(a) & set(b)) / max(len(set(a)), len(set(b)), 1)

    scored = [(t, overlap(query_lower, tl)) for t, tl in zip(titles, title_lower)]
    best_title, best_score = max(scored, key=lambda x: x[1])
    return best_title if best_score >= 0.5 else None


# ── Recommendation engine ──────────────────────────────────────────────────────
def recommend(movie_query, df, similarity, top_n=5):
    """
    Return top-N recommendations with similarity scores.
    Handles case differences and partial/fuzzy titles.
    """
    matched = find_closest_title(movie_query, df["title"].tolist())

    if matched is None:
        print(f"\n❌ '{movie_query}' not found. Try a different title.")
        return

    if matched.lower() != movie_query.lower():
        print(f"\n🔍 Showing results for: '{matched}' (closest match to '{movie_query}')")

    idx = df[df["title"] == matched].index[0]
    source_genres = df.iloc[idx]["genres"]

    # Pair every movie with its similarity score, exclude the query itself
    scored = [
        (df.iloc[i]["title"], df.iloc[i]["genres"], round(sim, 4))
        for i, sim in enumerate(similarity[idx])
        if i != idx
    ]
    scored.sort(key=lambda x: x[2], reverse=True)
    top = scored[:top_n]

    # ── Pretty output ──────────────────────────────────────────────────────────
    print(f"\n{'─'*50}")
    print(f"  🎬  Because you liked: {matched}")
    print(f"       Genres: {source_genres}")
    print(f"{'─'*50}")

    for rank, (title, genres, score) in enumerate(top, 1):
        bar_len = int(score * 20)
        bar = "█" * bar_len + "░" * (20 - bar_len)
        pct = int(score * 100)
        print(f"  {rank}. {title:<35} [{bar}] {pct:>3}%")
        print(f"     Genres: {genres}")
    print(f"{'─'*50}\n")


# ── Main loop ──────────────────────────────────────────────────────────────────
def main():
    df, similarity = train_model()
    print(f"\n🎥 Movie Recommender — {len(df)} titles loaded")
    print("   Type a movie name, or 'list' to browse, or 'quit' to exit.\n")

    while True:
        query = input("Enter movie name: ").strip()

        if not query:
            continue
        if query.lower() == "quit":
            print("Bye! 🎬")
            break
        if query.lower() == "list":
            cols = 3
            titles = df["title"].tolist()
            for i in range(0, len(titles), cols):
                row = titles[i:i+cols]
                print("  " + "   ".join(f"{t:<28}" for t in row))
            print()
            continue

        try:
            n_input = input("How many recommendations? [default 5]: ").strip()
            top_n = int(n_input) if n_input.isdigit() and int(n_input) > 0 else 5
        except Exception:
            top_n = 5

        recommend(query, df, similarity, top_n=top_n)


if __name__ == "__main__":
    main()